### ISSUE TITLE
[Bug] Possible bug in org-level metrics?

### ISSUE THREAD

**Issue by raffertyuy** [austenstone/copilot-usage#125]
### What happened?

There might be a problem with the organization level metrics.

Team level metrics work
```
  export-team-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Team Copilot Usage Metrics Export
        uses: austenstone/copilot-usage@v4
        with:
          github-token: ${{ secrets.VUE_APP_GITHUB_TOKEN }}
          enterprise: ${{ secrets.VUE_APP_GITHUB_ENT }}
          organization: callmegreg-demo-org
          team: pleasework
```

but Org level metrics doesn't work (even if I specify the org used above)
```
  export-org-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Organization Copilot Usage Metrics Export
        uses: austenstone/copilot-usage@v4
        with:
          github-token: ${{ secrets.VUE_APP_GITHUB_TOKEN }}
          enterprise: ${{ secrets.VUE_APP_GITHUB_ENT }}
          organization: callmegreg-demo-org
```

### Relevant log output

Run austenstone/copilot-usage@v4
Fetching Copilot usage for enterprise ***
Fetched Copilot usage data for 27 days (2024-09-14 to 2024-10-10)
Fetching Copilot details for organization callmegreg-demo-org
HttpError: Not Found - https://docs.github.com/rest/copilot/copilot-user-management#get-copilot-seat-information-and-settings-for-an-organization
    at /home/runner/work/_actions/austenstone/copilot-usage/v4/node_modules/@actions/github/node_modules/@octokit/request/dist-node/index.js:125:1
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at run (/home/runner/work/_actions/austenstone/copilot-usage/v4/src/run.ts:128:1)
